### PR TITLE
Travis-CI Script

### PR DESCRIPTION
**Pull request by ax3l**
GCC 4.8 to 7, clang and OSX.

Template, we can active CI as soon as we have a first CMake script in.

### CODE REVIEW

**Comment by ax3l** [comment]
@jeffhammond feel free to give me "Admin" access for this repo so I can control e.g. CI hooks for it as well.

**Comment by jeffhammond** [comment]
I will as soon as I can figure out where they moved the settings for that :rage1:

**Comment by ax3l** [comment]
I think in the collaborators tab where you added me is a dropdown option or so

**Comment by jeffhammond** [comment]
I think I need to create an organization in order to manage permissions properly 😞 
screen shot 2018-06-13 at 8 16 42 am

**Comment by jeffhammond** [comment]
As you probably noticed, I created an org, because I could not figure out another way.

**Comment by ax3l** [comment]
even better, would have suggested that as well :)

In the org you can also just add me to the owners.

**Comment by ax3l** [comment]
Nice, our top language is CMake so far.

**Comment by jeffhammond** [comment]
Yeah, don't remind me.  I am not a CMake fan but have no objections to you supporting it.  I will add Autotools support at some point.

**Comment by ax3l** [comment]
If you like I can also just output a `.pc` file for you if that helps with autotools integration downstream.

I think I would prefer staying with a single build system for the lib though, simply because one will never get the exact same result with two build systems. And that's bad downstream ("ok, which variant did you build again?") I am ok taking the responsibility with CMake, I think I am quite fluent with it.

**Comment by jeffhammond** [comment]
My goal is to write the implementation such that the build system can be trivial (require only C++11 compiler) so perhaps I'll just describe that build for CMake haters like me.

**Comment by ax3l** [comment]
Excellent, :+1: for that approach.

**Pull request merged**
